config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :transactions
  resources :portfolio_value_histories
  resources :exchanges
  resources :ownerships
  resources :stocks
  resources :users
  resources :trade
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/seed_users/:seed_id', to: 'users#prd_seed_users'
  get '/seed_stocks/:seed_id', to: 'stocks#prd_seed_stocks'
  get '/destroy_users', to: 'users#destroy_users'
  get '/destroy_stocks', to: 'stocks#destroy_stocks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exchange.rb
# == Schema Information
#
# Table name: exchanges
#
#  id            :bigint           not null, primary key
#  amount        :decimal(15, 2)
#  exchange_type :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :bigint           not null
#
# Indexes
#
#  index_exchanges_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Exchange < ApplicationRecord
  belongs_to :user
  enum exchange_type: [:deposit, :withdrawal]
  validate :user_can_make_exchange
  after_create :perform_exchange

  def user_can_make_exchange
    case exchange_type
    when "withdrawal"
      if amount > user.cash_balance
        errors.add "Cannot withdraw more money than is currently in your account."
      end
    end
  end

  def perform_exchange
    exchange_multiplier = self.deposit? ? 1 : -1
    user.increment(:cash_balance, amount * exchange_multiplier).save!
    PortfolioValueHistory.create(user: user, portfolio_value: user.portfolio_value)
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  skip_forgery_protection
  before_action :set_exchange, only: %i[ show edit update destroy ]

  # GET /exchanges or /exchanges.json
  def index
    @exchanges = Exchange.all.includes(:user)
    @exchanges = @exchanges.first(100)
  end

  # GET /exchanges/1 or /exchanges/1.json
  def show
  end

  # GET /exchanges/new
  def new
    @exchange = Exchange.new
    @exchange.user = current_user
  end

  # GET /exchanges/1/edit
  def edit
  end

  # POST /exchanges or /exchanges.json
  def create
    @exchange = Exchange.new(exchange_params)
    if @exchange.user.nil?
      @exchange.user = current_user
    end

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to '/', notice: "Exchange was successfully created." }
        format.json { render :show, status: :created, location: @exchange }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchanges/1 or /exchanges/1.json
  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to @exchange, notice: "Exchange was successfully updated." }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchanges/1 or /exchanges/1.json
  def destroy
    @exchange.destroy
    respond_to do |format|
      format.html { redirect_to exchanges_url, notice: "Exchange was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange
      @exchange = Exchange.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exchange_params
      params.require(:exchange).permit( :user_id, :exchange_type, :amount)
    end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.erb
<%= form_with(model: exchange) do |form| %>
  <% if exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
        <% exchange.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.radio_button :exchange_type, 'deposit', :checked => true %>
      <%= label :exchange_type_deposit, 'Deposit' %>
      <%= form.radio_button :exchange_type, 'withdrawal' %>
      <%= label :exchange_type_withdrawal, 'Withdrawal'%>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to 'Show', @exchange %> |
<%= link_to 'Back', exchanges_path %>

app/views/exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exchanges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Exchange date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchanges.each do |exchange| %>
      <tr>
        <td><%= exchange.user.name %></td>
        <td><%= exchange.exchange_type %></td>
        <td><%= exchange.amount %></td>
        <td><%= link_to 'Show', exchange %></td>
        <td><%= link_to 'Edit', edit_exchange_path(exchange) %></td>
        <td><%= link_to 'Destroy', exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange', new_exchange_path %>

app/views/exchanges/new.html.erb
<div class="login-modal">
<h1>New Exchange</h1>

<%= render 'form', exchange: @exchange %>

<button onclick="window.location.href='/'" class="btn btn-secondary">Back to Home</button>
</div>

app/views/exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @exchange.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @exchange.exchange_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @exchange.amount %>
</p>

<%= link_to 'Edit', edit_exchange_path(@exchange) %> |
<%= link_to 'Back', exchanges_path %>