config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :transactions
  resources :portfolio_value_histories
  resources :exchanges
  resources :ownerships
  resources :stocks
  resources :users
  resources :trade
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/seed_users/:seed_id', to: 'users#prd_seed_users'
  get '/seed_stocks/:seed_id', to: 'stocks#prd_seed_stocks'
  get '/destroy_users', to: 'users#destroy_users'
  get '/destroy_stocks', to: 'stocks#destroy_stocks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  caches_page :index
  
  def index
  	if current_user
  		@portfolio_history = PortfolioValueHistory.where("user_id = ?", current_user.id).select(:created_at, :portfolio_value)
  	end
  end
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
  <div class="login-modal">
  <p>Welcome, <%= current_user.name %>!</p>
  <div class="top-user-menu">
    <tr class="acts">
      <td><%= link_to "Make Deposit or Withdrawal", new_exchange_path, class: "btn btn-success" %></td>
      <td><%= link_to "Make Trade", new_transaction_path, class: "btn btn-success" %></td>
    </tr>
    <div>
      <br>
      Current cash balance: <%= current_user.cash_balance %>
      <br>
      Current portfolio value: <%= current_user.portfolio_value %>
      <br>
    </div>
  </div>
  <br>
  <h3>Portfolio History</h3>
  <%= line_chart [{name: "Portfolio History", data: @portfolio_history.inject({}) {|res, v| res[v[:created_at]] = v.portfolio_value; res}}],
                 curve: false, points: false, legend: false, width: "590px", height: "350px", colors: ["#5cb85c"], library: {backgroundColor: "transparent"}
  %>
  <br>
  <h3>List of all stocks owned by <%= current_user.name %></h3>
  <ul>
    <% current_user.stocks_ownership.each do |ownership| %>
      <li><%= ownership.stock.name %> | <%= ownership.stock.symbol %> | <%= ownership.stock.share_price %> |
        Amt: <%= ownership.num_shares %></li>
    <% end %>
  </ul>
  <br>
  <blockquote class="twitter-tweet" data-theme="dark">
    <p lang="en" dir="ltr">It’s inevitable <a href="https://t.co/eBKnQm6QyF">pic.twitter.com/eBKnQm6QyF</a></p>&mdash;
    Elon Musk (@elonmusk)
    <a href="https://twitter.com/elonmusk/status/1284291528328790016?ref_src=twsrc%5Etfw">July 18, 2020</a></blockquote>
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
<% else %>
    <div class="login-modal">
    <h1>Welcome to Stonk Market!</h1>
    <%= image_tag "doge-logo.png", class: "login-image" %>
    <br>
    <%= link_to "Sign Up", signup_path, class: "btn btn-success" %> or
    <%= link_to "Log In", login_path, class: "btn btn-success" %>
    </div>
<% end %>