config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :transactions
  resources :portfolio_value_histories
  resources :exchanges
  resources :ownerships
  resources :stocks
  resources :users
  resources :trade
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/seed_users/:seed_id', to: 'users#prd_seed_users'
  get '/seed_stocks/:seed_id', to: 'stocks#prd_seed_stocks'
  get '/destroy_users', to: 'users#destroy_users'
  get '/destroy_stocks', to: 'stocks#destroy_stocks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  skip_forgery_protection
  before_action :set_transaction, only: %i[ show ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  def new
    unless current_user.nil?
      @owned_stocks = current_user.stocks_ownership.where("num_shares > ?", 0)
    end
    @transaction = Transaction.new
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(user_id: transaction_params[:user_id], stock_id: transaction_params[:stock_id],
                                   num_shares: transaction_params[:num_shares],
                                   transaction_type: transaction_params[:transaction_type])
    if params[:stock_symbol].present?
      @transaction.stock = Stock.find_by_symbol params[:stock_symbol] || Stock.first
    elsif transaction_params[:stock_symbol].present?
      @transaction.stock = Stock.find_by_symbol transaction_params[:stock_symbol] || Stock.first
    end
    if @transaction.user.nil?
      @transaction.user = current_user
    end
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to root_path, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, notice: "Transaction unsuccessful. Please try again", status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:user_id, :stock_id, :num_shares, :transaction_type, :stock_symbol)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_display_stocks_all.erb
  <div class="table-scrollable-content">
  <table class="table table-light">
  <tbody>
    <% current_user.stocks_ownership.where("num_shares > ?", 0).each_with_index do |ownership, index| %>
      <% if index % 2 == 0%>
      <tr class="table-light">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <% else %>
      <tr class="table-secondary">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
  </table>
  <input type="hidden" id="table-type" name="table-type" value="all">
  </div>

app/views/transactions/_display_stocks_limited.erb
  <div class="table-scrollable-content">
  <table class="table table-light">
  <tbody>
    <% @ownerships = current_user.stocks_ownership.where("num_shares > ?", 0).first(5).each_with_index do |ownership, index| %>
      <% if index % 2 == 0%>
      <tr class="table-light">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <% else %>
      <tr class="table-secondary">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
  </table>
  <input type="hidden" id="table-type" name="table-type" value="limited">
  </div>

app/views/transactions/_footer.erb
<div class="back-button">
    <%= button_to 'Back to Home Page', root_path, :method => "get", class: "btn btn-secondary" %>
</div>

app/views/transactions/_footer.html.erb
<div class="back-button">
    <%= button_to 'Back to Home Page', root_path, :method => "get", class: "btn btn-secondary" %>
</div>

app/views/transactions/_form.html.erb
<p id="notice"><%= notice %></p>
<%= stylesheet_link_tag 'transactions'%>
<div>
<% if current_user %>
<%= form_with(model: transaction) do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="top">
  <div class="transaction-modal">
  <h1>New Transaction</h1>
  <div class="radio-input">
  <div class="form-check form-check-inline">
    <%= form.radio_button :transaction_type, 'buy', :checked => true, class: "form-check-input" %>
    <%= label :buy_selection, 'buy', class: "form-check-label"%>
  </div>
  <div class="form-check form-check-inline">
    <%= form.radio_button :transaction_type, 'sell', class: "form-check-input" %>
    <%= label :sell_selection, 'sell', class: "form-check-label" %>
  </div>
  </div>

  <div class="field">
    <%= form.label :stock_symbol, "Input Stock Symbol" %>
    <%= form.text_field :stock_symbol %>
  </div>
  <div class="field">
    <%= form.label :num_shares, "Number of Shares" %>
    <%= form.number_field :num_shares, min: 1 %>
  </div>
  <div class="field">
    <%= form.submit "Make Trade", class: 'btn btn-success btn-block'%>
  </div>
  
  </div>
  </div>
  <br>
  <% end %>
</div>

  <div class="bottom">
  <h2>List of Owned Stocks</h2>
  <br>
  <button id="close-modal-button" onclick="switchTables()" class="btn btn-success btn-block" data-remote="true">Show All Stocks</button>
  <!--NOTE: not sure if you need data-remote=true or remote=true since the js still works without it-->
  <table id="table-no-padding" class="table table-light">
    <thead class="table-dark">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Symbol</th>
    <th scope="col">Price</th>
    <th scope="col">Shares</th>
  </tr>
  </thead>
  </table>
  <div id="table-placeholder" class ="table-placeholder">
    <%= render 'display_stocks_limited', current_user: current_user%>
  </div>
<%end%>
<br>
</div>

<script>
function switchTables() {
var table_display, table_type;
table_display = document.getElementById("table-placeholder");
table_type = document.getElementById("table-type");
if (table_type.value == "limited") {
  table_display.textContent = '';
  table_display.insertAdjacentHTML('afterbegin', '<%= escape_javascript(render "display_stocks_all", current_user: current_user)%>');
  console.log("table_type.value: " + table_type.value);
}
else {
  console.log("table is already ALL: table_type.value: " + table_type.value);
}
}
</script>

app/views/transactions/_header.erb
<h1 class ="title">New Transaction</h1>
<p id="notice"><%= notice %></p>

app/views/transactions/_header.html.erb
<h1 class ="title">New Transaction</h1>
<p id="notice"><%= notice %></p>

app/views/transactions/_ownership.html.erb
      <% if ownership.id % 2 == 0%>
      <tr class="table-light">
        <%= render partial: 'stocks/stock', locals: {stock: ownership.stock }, cached: true %>
        <td><%= ownership.num_shares %></td>
      </tr>
      <% else %>
      <tr class="table-secondary">
        <%= render partial: 'stocks/stock', locals: { stock: ownership.stock }, cached: true %>
        <td><%= ownership.num_shares %></td>
      </tr>
      <%end%>

app/views/transactions/_show_stocks_all.erb
  <div class="table-scrollable-content">
  <table class="table table-light">
  <tbody>
    <% current_user.stocks_ownership.where("num_shares > ?", 0).each_with_index do |ownership, index| %>
      <% if index % 2 == 0%>
      <tr class="table-light">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <% else %>
      <tr class="table-secondary">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
  </table>
  </div>

app/views/transactions/_show_stocks_limited.erb
  <div class="table-scrollable-content">
  <table class="table table-light">
  <tbody>
    <% current_user.stocks_ownership.where("num_shares > ?", 0).first(20).each_with_index do |ownership, index| %>
      <% if index % 2 == 0%>
      <tr class="table-light">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <% else %>
      <tr class="table-secondary">
        <td><%= ownership.stock.name %></td>
        <td><%= ownership.stock.symbol %></td>
        <td><%= ownership.stock.share_price %></td>
        <td><%= ownership.num_shares %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
  </table>
  </div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.stock.symbol %></td>
        <td><%= transaction.user.name %></td>
        <td><%= transaction.transaction_type %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<%= stylesheet_link_tag 'transactions'%>
<%= render 'shared/background', header: nil, 
body: (render 'form', transaction: @transaction),
footer: (render 'footer') %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>